# Generated by Django 4.2 on 2023-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComedyTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='screening')),
                ('director', models.CharField(max_length=200)),
                ('actors', models.TextField()),
                ('producer', models.CharField(max_length=200)),
                ('production_date', models.DateTimeField()),
                ('release_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
