# Generated by Django 4.2 on 2023-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_rename_create_time_screening_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='image',
            field=models.ImageField(upload_to='screening'),
        ),
    ]
