# Generated by Django 4.2 on 2023-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artAndExpriens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artandexpriens',
            name='image',
            field=models.ImageField(upload_to='artAndExpriens'),
        ),
    ]
