# Generated by Django 4.1.5 on 2023-01-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='create_time',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='pulish_date',
            new_name='publish_date',
        ),
    ]
